tikv/rocksdb

- db/compaction_job.cc
Cherry pick [bug fix](https://github.com/facebook/rocksdb/pull/3017) from RocksDB.
> fix delete range bug

- CMakeLists.txt
- cmake/modules/FindNUMA.cmake
- cmake/modules/FindTBB.cmake
cherry-pick this [commit](https://github.com/facebook/rocksdb/commit/3e40a5e8325905e32b15a646d914a571ff2633d2).
> add missing config checks to CMakeLists.txt

- db/external_sst_file_ingestion_job.cc
- db/version_set.cc
- db/version_set.h
This is picked from https://github.com/facebook/rocksdb/commit/ecfca1ff597f1ee4a6ebdc5a7a076fff444606cf, but with a little change because of some differences between `facebook/rocksdb:master` and `pingcap/rocksdb:release`.
> Optimize external file ingestion

- table/block_based_filter_block.cc
- table/block_based_filter_block.h
- table/block_based_filter_block_test.cc
- table/block_based_table_builder.cc
- table/filter_block.h
- table/full_filter_block.h
- table/full_filter_block_test.cc
- table/partitioned_filter_block.cc
- table/partitioned_filter_block.h
Summary:
Close https://github.com/facebook/rocksdb/issues/3592
Closes https://github.com/facebook/rocksdb/pull/3614
Differential Revision: D7291706
fbshipit-source-id: 9dd8f40bd7716588e1e3fd6be0c2bc2766861f8c
> Ignore empty filter block when data block is empty

- db/compaction_picker.cc
- db/compaction_picker.h
- db/db_compaction_test.cc
- db/db_impl_compaction_flush.cc
Cherry pick 3 fixes related to `CompactFiles`.
> Cherry pick CompactFiles related fixes

- utilities/titandb/blob_file_iterator.h
- utilities/titandb/blob_file_size_collector.h
- utilities/titandb/blob_gc.h
- utilities/titandb/blob_gc_job.h
- utilities/titandb/blob_gc_job_test.cc
- utilities/titandb/blob_gc_picker.h
https://github.com/facebook/rocksdb/pull/4339
Align with RocksDB.
> titandb: use pragma once and fix gc test

- db/db_impl_compaction_flush.cc
- include/rocksdb/listener.h
Summary: Pull Request resolved: https://github.com/facebook/rocksdb/pull/4772
Differential Revision: D13428923
fbshipit-source-id: e351e9c5eea97816db25429e129357a8af90712a
(cherry picked from commit 4862720e08530b42354b328bfd1f6b962d9bedd5)
> Expose column family id to `FlushJobInfo`

- db/c.cc
- db/c_test.c
- db/compact_files_test.cc
- db/db_impl.h
- db/db_impl_compaction_flush.cc
- db/db_impl_readonly.h
- db/db_test.cc
- include/rocksdb/c.h
- include/rocksdb/db.h
- include/rocksdb/sst_file_reader.h
- include/rocksdb/table.h
- include/rocksdb/utilities/stackable_db.h
- java/rocksjni/statisticsjni.cc
- java/src/main/java/org/rocksdb/WriteBatchWithIndex.java
- java/src/test/java/org/rocksdb/WriteBatchWithIndexTest.java
- monitoring/statistics.cc
- table/sst_file_reader.cc
- table/sst_file_reader_test.cc
- tools/ldb_cmd.cc
- tools/sst_dump_tool.cc
Summary: Pull Request resolved: https://github.com/facebook/rocksdb/pull/4716
Differential Revision: D13207677
fbshipit-source-id: d0ccf5a66df6cbb07288b0c5ebad81fd9df3926b
(cherry picked from commit 2670fe8c73c66db6dad64bdf875e3342494e8ef2)
> Get `CompactionJobInfo` from CompactFiles

- db/db_impl_write.cc
- db/write_thread.h
- include/rocksdb/sst_dump_tool.h
- tools/ldb_cmd.cc
- tools/ldb_cmd_test.cc
- tools/sst_dump_test.cc
- tools/sst_dump_tool.cc
- tools/sst_dump_tool_imp.h
Please check the two commits from RocksDB.
> Cherry pick a bugfix and the ldb encryption support

- utilities/titandb/blob_file_size_collector_test.cc
- utilities/titandb/blob_file_test.cc
- utilities/titandb/blob_format_test.cc
- utilities/titandb/table_builder_test.cc
- utilities/titandb/testutil.h
- utilities/titandb/titan_db_test.cc
- utilities/titandb/util.h
- utilities/titandb/util_test.cc
- utilities/titandb/version_test.cc
1, Add a unit test for `BlobFileSizeCollector`
2, Add a unit test for `BlobFileReader`
3, Add a unit test for `BlobFileStateTransit`
4, Add a unit test for `TitanTableBuilder`
5, Add a unit test for `DbIter`
> Add 5 unit tests for Titan

- utilities/titandb/blob_gc_job.cc
- utilities/titandb/db_impl.cc
- utilities/titandb/db_impl_files.cc
- utilities/titandb/db_iter.h
- utilities/titandb/titan_db_test.cc
- add some logs
- add a test case: create a snapshot before flush, and test whether it is alright to get value after flush with that snapshot.
test passed after https://github.com/pingcap/rocksdb/pull/79 is merged.
> Titan: Add snapshot related test

- utilities/titandb/titan_db_test.cc
- utilities/titandb/version.cc
- utilities/titandb/version.h
Test description:
1. Generate a SST file using SstFileWriter
2. Open TitanDB
3. Insert some keys, verify data in DB
4. Ingest the file into the DB, verify data in DB
5. Verify no blob file is generated
6. Compact the DB using CompactRange(opt, nullptr, nullptr), verify data in DB
7. Verify blob file is generated, and it contain values with size larger than min_blob_size.
Also add export interface for BlobStorage and fix some function const quantifiers.
> Titan: Add IngestExternalFiles test

- build_tools/build_detect_platform
> build on ARM64

- memtable/inlineskiplist.h
Add more note for code.
Adjust position of **InsertPrevList()**, because **splice** maybe change when **recompute_height** is equal to **_0_**.
> Prev seek skiplist

- db/db_impl/db_impl.h
Move `WaitForFlushMemTable` API to public. It is needed for hotfix of https://github.com/pingcap/titan/issues/93
> Make WaitForFlushMemTable public

- env/env.cc
- include/rocksdb/env.h
- util/threadpool_imp.cc
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
> Add user priority

- .travis.yml
> Disable unnecessary java and cmake builds in travis

- .travis.yml
- db/db_impl/db_impl_write.cc
- options/options_helper.cc
Cherry-pick https://github.com/tikv/rocksdb/pull/171 and https://github.com/tikv/rocksdb/pull/170
> [Bug fix] Cherry-pick bugfix of multi-batch-write to tikv-4.x

- cloud/aws/aws_file.h
- cloud/db_cloud_test.cc
fix errors due to moving filename.h, logging.h, testharness.h
> Include fixes for changes in 6.4.tikv

- db/version_builder.cc
- db/version_builder.h
> improve consistency checks for deleted files (#189)

- .travis.yml
- db/db_impl/db_impl_compaction_flush.cc
- db/db_options_test.cc
- options/options_parser.cc
- table/table_test.cc
- tools/ldb_cmd_test.cc
I needed these changes to run `make` successfully.
See this issue which points out the problem and has the same patch solution but at a different point in time: https://github.com/facebook/rocksdb/issues/7352
> fix Clang 12 build errors

- db/version_builder.cc
- table/block_based/block_based_table_builder.cc
- table/block_based/block_based_table_reader.cc
- table/block_based/block_based_table_reader.h
* add compaction order check and data block cache check
Cherry-pick of #195
> Add compaction order check and data block cache check (#195)

- .travis.yml
- db/db_impl/db_impl_compaction_flush.cc
- db/db_options_test.cc
- options/options_parser.cc
- table/table_test.cc
- tools/ldb_cmd_test.cc
Cherry pick https://github.com/tikv/rocksdb/pull/194
---
I needed these changes to run `make` successfully.
See this issue which points out the problem and has the same patch solution but at a different point in time: https://github.com/facebook/rocksdb/issues/7352
Signed-off-by: Greg Weber <greg@pingcap.com>
Co-authored-by: yiwu-arbug <yiwu@pingcap.com>
> fix Clang 12 build errors (#194)

- db/db_impl/db_impl.cc
- include/rocksdb/listener.h
Add picked level for ingestion job info
> Add picked level for ingestion job info

- db/db_test_util.cc
- db/db_test_util.h
- encryption/encryption.cc
- encryption/in_memory_key_manager.h
- env/env_basic_test.cc
- file/filename.cc
- file/filename.h
- include/rocksdb/encryption.h
- test_util/testutil.cc
- test_util/testutil.h
pick https://github.com/tikv/rocksdb/commit/93e89a58edb820f2daa15362120617e49ef6ddd6 https://github.com/tikv/rocksdb/commit/00874ebfb608016df966225e922078a8f2df3fd1 https://github.com/tikv/rocksdb/commit/5d559f08a5dd24c2d814d873d30ee4842ebc2d20 into 6.4.tikv branch.
> Pick Atomize Rename operation related PRs into tikv-4.x
