tikv/rocksdb

db/db_impl_write.cc
Summary: Closes https://github.com/facebook/rocksdb/pull/2862
Differential Revision: D5805638
Pulled By: yiwu-arbug
fbshipit-source-id: 72d38c74395690023a719f400daff01527645a17
=> Fix missing BYTES_PER_WRITE for pipeline write

db/db_iter.cc, db/db_iter_test.cc, include/rocksdb/options.h, options/options.cc
Implement lower bound pr in RocksDB is [here](https://github.com/facebook/rocksdb/pull/3074).
Fix tombstone scans in SeekForPrev outside prefix is [this](https://github.com/facebook/rocksdb/pull/3067).
=> 5.7/cherry pick lower bound for iterator

db/db_compaction_test.cc, db/db_impl.cc, db/version_set.cc, include/rocksdb/convenience.h
Cherry-pick from [rocksdb](https://github.com/facebook/rocksdb/commit/78d1a5ec7263e380700b5fa36b2ffcd1cb265a2f).
=> Preserve overlapping file endpoint invariant

db/convenience.cc, db/db_compaction_test.cc, db/db_impl.cc, db/db_impl.h, include/rocksdb/convenience.h, include/rocksdb/db.h
Summary:
Using `DeleteFilesInRange` to delete files in a lot of ranges can be slow, because
`VersionSet::LogAndApply` is expensive.
This PR adds a new `DeleteFilesInRange` function to delete files in multiple
ranges at once.
Close https://github.com/facebook/rocksdb/issues/2951
Closes https://github.com/facebook/rocksdb/pull/3431
Differential Revision: D6849228
fbshipit-source-id: daeedcabd8def4b1d9ee95a58266dee77b5d68cb
=> [cherry-pick] Delete files in multiple ranges at once

db/external_sst_file_ingestion_job.cc
Summary:
Fsync after writing global sequence number to the ingestion file in ExternalSstFileIngestionJob. Otherwise the file metadata could be incorrect.
Closes https://github.com/facebook/rocksdb/pull/3644
Differential Revision: D7373813
Pulled By: sagar0
fbshipit-source-id: 4da2c9e71a8beb5c08b4ac955f288ee1576358b8
=> [Cherry-Pick] Fsync after writing global seq number in ExternalSstFileIngestionJob

table/block_based_filter_block.cc
Summary:
Our valgrind continuous test found an interesting leak which got introduced in #3614. We were adding the prefix key before saving the previous prefix start offset, due to which previous prefix offset is always incorrect. Fixed it by saving the the previous sate before adding the key.
Closes https://github.com/facebook/rocksdb/pull/3660
Differential Revision: D7418698
Pulled By: sagar0
fbshipit-source-id: 9933685f943cf2547ed5c553f490035a2fa785cf
=> Fix a leak in FilterBlockBuilder when adding prefix

util/file_reader_writer.cc
Summary:
We don't do fsync() after truncate in direct I/O writeable file (in fact we don't do any fsync ever). This can cause metadata not persistent to disk after the file is generated. We call it instead.
Closes https://github.com/facebook/rocksdb/pull/3500
Differential Revision: D6981482
Pulled By: siying
fbshipit-source-id: 7e2b591b7e5dd1b96fc0775515b8b9e6092980ef
=> [cherry-pick] Direct I/O writable file should do fsync in Close()

db/column_family.cc, db/column_family.h, db/compaction.cc, db/compaction.h, db/compaction_job.cc, db/compaction_job_test.cc, db/compaction_picker.cc, db/compaction_picker.h, db/compaction_picker_universal.cc, db/db_impl.h, db/db_impl_compaction_flush.cc, db/db_impl_debug.cc, db/db_range_del_test.cc, include/rocksdb/options.h
Summary:
Sometimes we want to compact files as fast as possible, but don't want to set a large `max_subcompactions` in the `DBOptions` by default.
I add a `max_subcompactions` options to `CompactionOptions` so that we can choose a proper concurrency dynamically.
Closes https://github.com/facebook/rocksdb/pull/3775
Differential Revision: D7792357
fbshipit-source-id: 94f54c3784dce69e40a229721a79a97e80cd6a6c
=> [Cherry-Pick] Add max_subcompactions as a compaction option

db/c.cc, memtable/inlineskiplist.h
Fixup build failures on C++ 8.1 (used by Arch).
---
Summary:
Fix the following gcc-8 warnings:
- conflicting C language linkage declaration [-Werror]
- writing to an object with no trivial copy-assignment [-Werror=class-memaccess]
- array subscript -1 is below array bounds [-Werror=array-bounds]
Solves https://github.com/facebook/rocksdb/issues/3716
Closes https://github.com/facebook/rocksdb/pull/3736
Differential Revision: D7684161
Pulled By: yiwu-arbug
fbshipit-source-id: 47c0423d26b74add251f1d3595211eee1e41e54a
=> Build successfully on C++ 8.1

db/db_compaction_test.cc, db/db_flush_test.cc, db/db_impl.h, db/db_impl_compaction_flush.cc, db/db_impl_debug.cc, db/db_test.cc, db/listener_test.cc, include/rocksdb/options.h, utilities/transactions/transaction_test.cc
Cherry-Pick: https://github.com/facebook/rocksdb/pull/4297
Summary:
Basically at the moment it seems it's possible to cause write stall by calling flush (either manually vis DB::Flush(), or from Backup Engine directly calling FlushMemTable() while background flush may be already happening.
One of the ways to fix it is that in DBImpl::CompactRange() we already check for possible stall and delay flush if needed before we actually proceed to call FlushMemTable(). We can simply move this delay logic to separate method and call it from FlushMemTable.
This is draft patch, for first look; need to check tests/update SyncPoints and most certainly would need to add allow_write_stall method to FlushOptions().
Pull Request resolved: https://github.com/facebook/rocksdb/pull/4297
Differential Revision: …
=> Avoiding write stall caused by manual flushes (#4297)

utilities/titandb/version.cc, utilities/titandb/version.h, utilities/titandb/version_builder.cc
The original implementation didn't evict blob file handle from cache when it was deleted such that the disk space will not be reclaimed as soon as possible.
=> Evict blob file handle from cache when it was deleted

db/db_impl_compaction_flush.cc, db/db_test.cc
Summary:
CompactFiles() may block auto compaction which could cuase DB hang when it
reachs level0_stop_writes_trigger.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/4940
Differential Revision: D13929648
Pulled By: cooldoger
fbshipit-source-id: 10842df38df3bebf862cd1a120a88ce961fdd381
(cherry picked from commit c9a52cbdc8fc8fffa793de29a8086f7a7ca802f6)
=> Fix potential DB hang while using CompactFiles (#4940)

options/options_settable_test.cc, utilities/titandb/blob_file_iterator_test.cc, utilities/titandb/blob_file_reader.cc, utilities/titandb/blob_file_size_collector_test.cc, utilities/titandb/blob_file_test.cc, utilities/titandb/db_impl.cc, utilities/titandb/table_builder_test.cc, utilities/titandb/util.cc, utilities/titandb/util.h, utilities/titandb/version_set.cc
Summary:
Fix: compression util functions now return `CacheAllocationPtr`.
Fix: WritableFileWriter constructor now require file name.
Fix options.original_table_factory not ignored in options_settable_test.
Tested Plan:
Run `make all check titandb_check` locally
=> Fix Titan compatibility with rocksdb 5.18

db/db_impl.cc, db/db_impl.h, utilities/titandb/db_impl.cc
Summary:
The `allow_refresh` param is missing when Titan create `DBIter`, and Titan end up passing nullptr as `super_version`. Fixing it. Also fix `TitanSnapshot` and `InternalIterator` double cleanup of `super_version`.
Test Plan:
`make titandb_check`
=> Titan: Fix iterator fail to pass SuperVersion to underlying iterator

utilities/titandb/db_iter.h
Summary:
Use `PRIu64` macro instead of `%lu` to fix build error (e.g. https://travis-ci.org/pingcap/rust-rocksdb/jobs/520044867).
Test Plan:
build.
=> Titan: fix error message formatting

utilities/titandb/db_impl.cc, utilities/titandb/db_impl.h, utilities/titandb/titan_db_test.cc
* fix missing DropColumnFamily method
* add test for API behaviour of DropColumnFamily: outstanding CF handle should be able to read after it's dropped.
it will raise `GetSuperVersion failed` panic for now.
this broken test should be resolved by reserving ColumnFamilyData after drop, and reserving Blob file after drop.
=> Titan: Add ReadAfterDropCF test

utilities/titandb/db_impl.cc, utilities/titandb/db_impl.h
Found existing implementation for `DropColumnFamily` in `rocksdb/utilities/titandb/db.h`,
therefore revert redundant updates to TitanDBImpl as an amendment to #87.
=> Titan: remove DropColumnFamily override

include/rocksdb/options.h, options/cf_options.cc, options/cf_options.h, options/options_settable_test.cc, table/sst_file_writer.cc, utilities/titandb/db_impl.cc, utilities/titandb/db_impl.h, utilities/titandb/titan_db_test.cc
Summary:
This is to remove intrusive change to core rocksdb. The `original_table_factory` option was added so that `SstFileWriter` can use `BlockBasedTableFactory` instead of `TitanTableFactory` to generate sst file. We now return original table factory through `GetOptions()` API and user can pass it back to `SstTableWriter`.
Test Plan:
Updated test.
=> Titan: Remove DBOptions::orignal_table_factory

utilities/titandb/blob_file_builder.cc, utilities/titandb/blob_file_builder.h, utilities/titandb/blob_file_iterator.cc, utilities/titandb/blob_file_iterator.h, utilities/titandb/blob_format.cc, utilities/titandb/blob_format.h, utilities/titandb/blob_gc_job_test.cc
Summary:
Adding 4 bytes magic number and 4 bytes version as header of blob files. This is same as the first 8 bytes of blob files of BlobDB. Benefits:
* Enable us to update file format later on.
* It will make us easier to distinguish our blob file and BlobDB blob file, if we will later merge into upstream.
Test Plan:
Existing tests
=> Titan: Add blob file header

utilities/titandb/db_iter.h, utilities/titandb/titan_db_test.cc
As a follow-up PR on #91, fix the obselete while-loop and status check in `TitanDBIterator`.
Also add `DBIterSeek` unit test to cover all seek methods iterator provides.
=> Titan: Fix iterator retrying and add seek related test

utilities/titandb/version_set.cc
Summary:
Fixing two issues to lead to crash if obsolete files detected on recovery:
1. `obsolete_files_` is a `std::list` and its iterator will be invalidate after erasing an item from the list. Use the return value from `erase()` to continue iterate.
2. Similarly, `BlobStorage::files_` should not be modify while iterating. Move `DeleteBlobFile` logic out of the loop of checking for obsolte files.
Test Plan:
`TitanDBTest::Basic` was failing on my side as it triggered a GC and obsolete some files before restart. Make sure it is passing now.
=> Titan: fix crash on recover when obsolete file exists

HISTORY.md, db/db_impl.cc, db/db_impl.h, db/db_impl_open.cc, db/external_sst_file_ingestion_job.cc, db/external_sst_file_ingestion_job.h
Summary:
It it not safe to assume application had sync the SST file before ingest
it into DB. Also the directory to put the ingested file needs to be
fsync, otherwise the file can be loss. For integrity of RocksDB we need
to sync the ingested file and directory before apply the change to
manifest.
Test Plan:
Test ingest file with ldb command and observe fsync/fdatasync in strace
output. Tried both move_files=true and move_files=false.
=> Fix ingested file and direcotry not being sync

HISTORY.md, db/db_impl.cc, db/db_impl.h, db/db_impl_open.cc, db/external_sst_file_ingestion_job.cc, db/external_sst_file_ingestion_job.h
Summary:
It it not safe to assume application had sync the SST file before ingest
it into DB. Also the directory to put the ingested file needs to be
fsync, otherwise the file can be loss. For integrity of RocksDB we need
to sync the ingested file and directory before apply the change to
manifest.
Test Plan:
Test ingest file with ldb command and observe fsync/fdatasync in strace
output. Tried both move_files=true and move_files=false.
=> Fix ingested file and direcotry not being sync (#96)

memtable/inlineskiplist.h
Signed-off-by: Little-Wallace liuwei@pingcap.com
When the iterator read keys in reverse order, each **Prev()** function cost _**O**_(log **n**) times. So we add prev pointer for every node in skiplist to improve the **Prev()** function.
=> add prev pointer for inline skiplist

db/c.cc, include/rocksdb/c.h, include/rocksdb/memtablerep.h, memtable/doubly_skiplist.h, memtable/inlineskiplist_test.cc, memtable/skiplistrep.cc
Signed-off-by: Little-Wallace liuwei@pingcap.com
When the iterator read keys in reverse order, each Prev() function cost O(log n) times. So I add prev pointer for every node in skiplist to improve the Prev() function.
=> Doubly skiplist for reverse scan

db/db_impl.cc, db/db_impl.h, db/db_impl_compaction_flush.cc, db/db_impl_files.cc, db/obsolete_files_test.cc
Summary:
purge_queue_ maybe contains thousands sst files, for example manual compact a range. If full scan is triggered at the same time and the total sst files number is large, RocksDB will be blocked at https://github.com/facebook/rocksdb/blob/master/db/db_impl_files.cc#L150 for several seconds. In our environment we have 140,000 sst files and the manual compaction delete about 1000 sst files, it blocked about 2 minutes.
Commandeering https://github.com/facebook/rocksdb/issues/5290.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/5796
Differential Revision: D17357775
Pulled By: riversand963
fbshipit-source-id: 20eacca917355b8de975ccc7b1c9a3e7bd5b201a
=> fast look up purge_queue (#5796)

logging/logging.h
Summary:
Source code path in info log is not truncated to the correct length. Fixing it. 
Test Plan:
Build and run db_bench. Before:
```
2019/09/18-21:32:34.631181 7fdd42df6700 [_impl/db_impl_write.cc:1654] [default] New memtable created with log file: #9. Immutable memtables: 0.
```
After:
```
2019/09/18-21:36:09.226532 7f141b5f6700 [/db_impl/db_impl_write.cc:1654] [default] New memtable created with log file: #9. Immutable memtables: 0.
```
=> Fix info log source file display length

db/compaction_picker.cc, db/db_compaction_test.cc
Summary:
Temporarily disable intra-L0 compaction to avoid data corruption issue caused by intra-L0 compaction compacting ingested file and place the result at wrong position in L0.
Test Plan:
The disabled intra-L0 tests will fail with the change.
=> Disable Intra-L0 compaction

HISTORY.md, db/db_flush_test.cc, db/db_impl/db_impl.h, db/db_impl/db_impl_compaction_flush.cc, db/flush_job.cc, db/flush_job.h, db/flush_job_test.cc, db/memtable.h, db/memtable_list.cc, db/memtable_list.h, db/memtable_list_test.cc, include/rocksdb/listener.h
Summary:
When there are concurrent flush job on the same CF, `OnFlushCompleted` can be called before the flush result being install to LSM. Fixing the issue by passing `FlushJobInfo` through `MemTable`, and the thread who commit the flush result can fetch the `FlushJobInfo` and fire `OnFlushCompleted` on behave of the thread actually writing the SST.
Fix https://github.com/facebook/rocksdb/issues/5892
Pull Request resolved: https://github.com/facebook/rocksdb/pull/5908
Test Plan: Add new test. The test will fail without the fix.
Differential Revision: D17916144
Pulled By: riversand963
fbshipit-source-id: e18df67d9533b5baee52ae3605026cdeb05cbe10
=> Fix OnFlushCompleted fired before flush result write to MANIFEST (#5908)

HISTORY.md, db/column_family.cc, db/compaction_picker.cc, db/compaction_picker.h, db/compaction_picker_fifo.cc, db/compaction_picker_fifo.h, db/compaction_picker_test.cc, db/compaction_picker_universal.cc, db/compaction_picker_universal.h, db/db_blob_index_test.cc, db/db_compaction_test.cc, db/db_flush_test.cc, db/db_impl_compaction_flush.cc, db/db_impl_debug.cc, db/db_impl_write.cc, db/db_iter.cc, db/db_write_test.cc, db/external_sst_file_test.cc, db/internal_stats.cc, db/internal_stats.h, include/rocksdb/options.h, utilities/persistent_cache/block_cache_tier.h, utilities/persistent_cache/block_cache_tier_file.h
Summary:
Cherry-picking intra-L0 corruption fix, unordered_write+two_write_queue fix and their dependencies. Also cherry-picking some compile error fix to resolve errors with clang11. Full list of changes:
```
76bf98cee 2019-11-26 yiwu@pingcap.com     Fix DBFlushTest::FireOnFlushCompletedAfterCommittedResult hang (#6018)
04f136916 2019-11-26 harrywong@live.com   Removed const fields in copyable classes (#5095)
3d3cee167 2019-11-26 siying.d@fb.com      Rename InternalDBStatsType enum names (#5779)
08ec346ed 2019-11-26 xy.tao@outlook.com   Fix blob context when db_iter uses seek (#6051)
bede6cbc6 2019-11-26 bupt2013211450@gma.. fix unstable unittest caused by #5958 (#6061)
f3b7b6395 2019-11-26 bupt2013211450@gma.. Fix corruption with intra-L0 on ingested files (#5958)
c1e75bb53 2019-11-26 …
```
=> Cherry-pick intra-L0 corruption fix and other changes into tikv-3.0 branch

.travis.yml
encounter error for CI job `cmake-mingw`
```
/tmp/ccqyUnkN.s: Assembler messages:
/tmp/ccqyUnkN.s:6284: Error: invalid register for .seh_savexmm
/tmp/ccqyUnkN.s:6286: Error: invalid register for .seh_savexmm
/tmp/ccqyUnkN.s:6288: Error: invalid register for .seh_savexmm
CMakeFiles/rocksdb.dir/build.make:581: recipe for target 'CMakeFiles/rocksdb.dir/db/internal_stats.cc.obj' failed
```
Fix it by https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65782
=> fix invalid register for .seh_savexmm

db/db_basic_test.cc, db/db_test.cc, db/db_test_util.cc, db/db_test_util.h, db/internal_stats.cc, db/internal_stats.h, db/snapshot_impl.h, include/rocksdb/db.h
Summary:
Add oldest snapshot sequence property, so we can use `db.GetProperty("rocksdb.oldest-snapshot-sequence")` to get the sequence number of the oldest snapshot.
Cherry-pick of  https://github.com/facebook/rocksdb/pull/6228
=> Add oldest snapshot sequence property (#6228)

HISTORY.md, db/db_impl/db_impl.cc, db/db_options_test.cc, db/db_test2.cc, db/error_handler.cc, db/error_handler_test.cc, db/file_indexer.cc, db/version_set.cc, file/sst_file_manager_impl.cc
Cherry-picking the following changes:
```
8a2f1f23f 2020-02-04 anand76@devvm1373... Force a new manifest file if append to current one fails (#6331)
7e9ca30c8 2020-02-04 siying.d@fb.com      Bug when multiple files at one level contains the same smallest key (#6285)
cb831a2c5 2020-02-04 ltamasi@fb.com       Adjust thread pool sizes when setting max_background_jobs dynamically (#6300)
```
=> Cherry-pick recent rocksdb fixes from upstream into tikv master branch

.travis.yml, HISTORY.md, db/db_impl.cc, db/db_impl_compaction_flush.cc, db/db_options_test.cc, db/db_test2.cc, db/error_handler.cc, db/error_handler_test.cc, db/file_indexer.cc, db/version_set.cc, util/sst_file_manager_impl.cc
Cherry-picking the following fixes:
```
b5b81f993 2020-02-04 anand76@devvm1373... Force a new manifest file if append to current one fails (#6331)
50f6b2473 2020-02-04 siying.d@fb.com      Bug when multiple files at one level contains the same smallest key (#6285)
aeabee9a8 2020-02-04 ltamasi@fb.com       Adjust thread pool sizes when setting max_background_jobs dynamically (#6300)
```
=> Cherry-pick recent rocksdb fixes from upstream into tikv-3.x branch

db/db_impl/db_impl_write.cc, include/rocksdb/statistics.h, monitoring/statistics.cc
Add WAL write duration metric
UCP [#5751](https://github.com/tikv/tikv/issues/6541)
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>
=> Add WAL write duration metric

tools/db_bench_tool.cc
Summary:
Fix missing check for openssl in db_bench.
Test Plan:
build without openssl
=> Fix build error when build wihtout openssl

env/env_encryption.cc, include/rocksdb/perf_context.h
Summary:
Add `encrypt_data_time` and `decrypt_data_time` perf_context counters to time encryption/decryption time when `EnvEncryption` is enabled.
Test Plan:
CI
=> Add counter in perf_context to time cipher time

CMakeLists.txt, Makefile, encryption/encryption.cc, encryption/encryption.h, encryption/encryption_test.cc, include/rocksdb/encryption.h
Summary:
Instead of using openssl's raw `AES_encrypt` and `AES_decrypt` API, which is a low level call to encrypt or decrypt exact one block (16 bytes), we change to use the `EVP_*` API. The former is deprecated, and will use the default C implementation without AES-NI support. Also the EVP API is capable of handing CTR mode on its own.
Test Plan:
will add tests
=> encryption: change to use openssl EVP API

db/external_sst_file_test.cc, table/block_based/block.cc, table/block_based/block.h
Summary:
On reading an ingested SST file, `DataBlockIter` will replace seqno encoded in a key with global seqno. However, if the original seqno was part of the prefix used for the next key, the global seqno is by mistake used as part of the prefix to construct the next key, causing wrong result being returned. Although at this point it is only software error while data in the file is not corrupted, the issue can further cause compaction output out of order and corrupted result when the ingested SST participated in compaction. Fixing the issue by save the actual seqno and restore it before the key being used as prefix to construct next key.
The unit test is by Little-Wallace from https://github.com/facebook/rocksdb/issues/6666. Fixing https://github.com/facebook/rocksdb/issues/6666.
Pull …
=> Fix wrong key being read on ingested file with global seqno and delta encoding (#6669)

db/external_sst_file_test.cc, table/block_based/block.cc, table/block_based/block.h
Summary:
On reading an ingested SST file, `DataBlockIter` will replace seqno encoded in a key with global seqno. However, if the original seqno was part of the prefix used for the next key, the global seqno is by mistake used as part of the prefix to construct the next key, causing wrong result being returned. Although at this point it is only software error while data in the file is not corrupted, the issue can further cause compaction output out of order and corrupted result when the ingested SST participated in compaction. Fixing the issue by save the actual seqno and restore it before the key being used as prefix to construct next key.
The unit test is by Little-Wallace from https://github.com/facebook/rocksdb/issues/6666. Fixing https://github.com/facebook/rocksdb/issues/6666.
Pull …
=> Fix wrong key being read on ingested file with global seqno and delta encoding (facebook#6669)

env/env_encryption.cc, include/rocksdb/perf_context.h
Summary:
Add `encrypt_data_time` and `decrypt_data_time` perf_context counters to time encryption/decryption time when `EnvEncryption` is enabled.
Test Plan:
CI
=> Add counter in perf_context to time cipher time (#158)

CMakeLists.txt, Makefile, encryption/encryption.cc, encryption/encryption.h, encryption/encryption_test.cc, include/rocksdb/encryption.h
Summary:
Instead of using openssl's raw `AES_encrypt` and `AES_decrypt` API, which is a low level call to encrypt or decrypt exact one block (16 bytes), we change to use the `EVP_*` API. The former is deprecated, and will use the default C implementation without AES-NI support. Also the EVP API is capable of handing CTR mode on its own.
Test Plan:
will add tests
=> encryption: change to use openssl EVP API (#156)

encryption/encryption.cc
Summary:
Fix NewRandomRWFile and ReuseWritableFile misuse of `GetFile()` and `NewFile()`. See inline comments.
Test Plan:
manual test with tikv
=> Fix NewRandomRWFile and ReuseWritableFile in KeyManagedEncryptedEnv

options/options_helper.cc
This is a bug that I did not pass `enable_multi_thread_write` to the function `BuildDBOptions`, which may cause some case we can not get the right value of `enable_multi_thread_write`  from `DBOptions`
=> [BUG] Pass enable_multi_thread_write to BuildDBOptions

.travis.yml, db/db_impl/db_impl_write.cc
I created `memtable_write_group` in a wrong position, so it was dropped before this thread began running `STATE_PARALLEL_MEMTABLE_WRITER `.   If there are more than one thread trying to insert keys to `RocksDB` and every of them have more than one `WriteBatch`, the process will crash because of accessing an invalid memory address.
=> Fix life time of `memtable_write_group`

db/compaction/compaction.cc, include/rocksdb/compaction_filter.h
Signed-off-by: qupeng <qupeng@pingcap.com>
=> compaction_filter: add bottommost_level into context

HISTORY.md, db/external_sst_file_test.cc, table/block.cc, table/block.h
Summary:
`IterKey::UpdateInternalKey()` is an error-prone API as it's
incompatible with `IterKey::TrimAppend()`, which is used for
decoding delta-encoded internal keys. This PR stops using it in
`BlockIter`. Instead, it assigns global seqno in a separate `IterKey`'s
buffer when needed. The logic for safely getting a Slice with global
seqno properly assigned is encapsulated in `GlobalSeqnoAppliedKey`.
`BinarySeek()` is also migrated to use this API (previously it ignored
global seqno entirely).
Pull Request resolved: https://github.com/facebook/rocksdb/pull/6843
Test Plan:
benchmark setup -- single file DBs, in-memory, no compression. "normal_db"
created by regular flush; "ingestion_db" created by ingesting a file. Both
DBs have same contents.
```
$ TEST_TMPDIR=/dev/shm/normal_db/ …
```
=> avoid `IterKey::UpdateInternalKey()` in `BlockIter` (#6843)

db/version_set.h
Related to tikv/rust-rocksdb#517 and tikv/rocksdb#182
Adds code used in compiling with [rocksdb~6.4.tikv](https://github.com/tikv/rocksdb/tree/6.4.tikv) along with [rocksdb~6.4.cloud](https://github.com/tikv/rocksdb/tree/6.4.cloud)
- Makes public the struct LogReporter so that it can be accessed by [rocksdb~6.4.cloud/cloud/manifest_reader.cc#L114](https://github.com/tikv/rocksdb/blob/6a7c514453e3e3e1c3bb57c18d8e0280089ccdcd/cloud/manifest_reader.cc#L114)
Signed-off-by: Devdutt Shenoi <devdutt@outlook.in>
=> Code changes to plugin rocksdb_cloud

cloud/aws/aws_env.cc, cloud/aws/aws_env.h, cloud/aws/aws_file.h, cloud/aws/aws_log.cc, cloud/cloud_env.cc, cloud/cloud_env_impl.h, cloud/cloud_env_wrapper.h, cloud/cloud_manifest.cc, cloud/cloud_manifest_test.cc, cloud/db_cloud_impl.cc, cloud/db_cloud_test.cc, cloud/filename.h, cloud/manifest_reader.cc, cloud/purge.cc, include/rocksdb/cloud/cloud_env_options.h
Used in PR tikv/rust-rocksdb#517 and tikv/rocksdb#181
Adds code used in compiling with [rocksdb~6.4.tikv](https://github.com/tikv/rocksdb/tree/6.4.tikv) along with [rocksdb~6.4.cloud](https://github.com/tikv/rocksdb/tree/6.4.cloud)
=> Compile cloud features with 6.4.tikv branch

CMakeLists.txt, HISTORY.md, TARGETS, db/compaction/compaction.cc, db/compaction/compaction.h, db/compaction/compaction_job.cc, db/compaction/compaction_picker_test.cc, db/compaction/sst_partitioner.cc, db/db_compaction_test.cc, include/rocksdb/options.h, include/rocksdb/sst_partitioner.h, options/cf_options.cc, options/cf_options.h, options/options.cc, options/options_settable_test.cc, src.mk
Summary:
SST Partitioner interface that allows to split SST files during compactions.
It basically instruct compaction to create a new file when needed. When one is using well defined prefixes and prefixed way of defining tables it is good to define also partitioning so that promotion of some SST file does not cover huge key space on next level (worst case complete space).
Pull Request resolved: https://github.com/facebook/rocksdb/pull/6957
Reviewed By: ajkr
Differential Revision: D22461239
fbshipit-source-id: 9ce07bba08b3ba89c2d45630520368f704d1316e
=> SST Partitioner interface that allows to split SST files (#6957)

HISTORY.md, db/c_test.c, db/db_range_del_test.cc, db/memtable_list.cc, db/write_batch.cc, db/write_batch_test.cc, include/rocksdb/c.h, include/rocksdb/db.h, include/rocksdb/utilities/write_batch_with_index.h, java/src/main/java/org/rocksdb/WriteBatchWithIndex.java, java/src/test/java/org/rocksdb/WriteBatchWithIndexTest.java, utilities/write_batch_with_index/write_batch_with_index.cc
Cherry-picking the following fixes for `DeleteRange`. The last one affect correctness.
```
12210b819 2020-08-11 andrewkr@fb.com      validate range tombstone covers positive range (#6788)
ad53352ce 2020-08-11 andrewkr@fb.com      Return NotSupported from WriteBatchWithIndex::DeleteRange (#5393)
853730c27 2020-08-11 mm304321141@gmail... Fix RangeDeletion bug (#6062)
```
=> Cherry-pick DeleteRange fixes from up to rockcsdb 6.12

db/write_batch.cc, db/write_batch_internal.h, include/rocksdb/write_batch.h
I want to use format of rocksdb::WriteBatch to encode key-value pairs of TiKV, and I need an more effective method to copy data from Entry to WriteBatch directly so that I could avoid CPU cost of decode.
=> Add Iterator and Append method for WriteBatch

db/version_builder.cc, db/version_builder.h
This PR optimizes consistency checks performance for the case with a lot of deleted files. 
When doing `DeleteFilesInRange` with `force_consistency_checks` on for a large range which spans about 16.5K SST files, we found it spent most of the time in `LogAndApply`(the time in red rectangle).
In `CheckConsistencyForDeletes`, it traverses the whole LSM to check if the file existed in the previous version for every deleted file. In the case of a lot of deleted files such as `DeleteFilesInRange`, it would waste too much time on this operation. Even worse, it is done with db mutex held, so it may greatly affect the foreground write performance.
After making the check in batch with only one round of traverse of the LSM, the time is greatly reduced.
=> Optimize consistency checks for deleted files

db/version_builder.cc, table/block_based/block_based_table_builder.cc, table/block_based/block_based_table_reader.cc, table/block_based/block_based_table_reader.h
Add checks to avoid wrongly mapping block cache populating `get` and `iterator` further., for more information of the wrongly mapping block cache, see https://github.com/facebook/rocksdb/issues/7405
Add check logic:
- check key order of compaction output
- compare data block's first key with the block index handle's key when retrieving data block
=> Add compaction order check and data block cache check

utilities/rate_limiters/write_amp_based_rate_limiter.cc
So that we can use a huge value as upper bound without losing the ability to adapt to normal pressure.
=> Use absolute value as lower bound for WriteAmpBasedRateLimiter's limit

HISTORY.md, db/db_impl/db_impl.cc, db/db_impl/db_impl_compaction_flush.cc, db/db_options_test.cc, options/db_options.cc, options/db_options.h, options/options_helper.cc
Cherry-picking facebook/rocksdb#6701
Summary:
1. Add changes so that max_background_flushes can be set dynamically.
2. Add a testcase DBOptionsTest.SetBackgroundFlushThreads which set the
max_background_flushes dynamically using SetDBOptions.
TestPlan:  1. make -j64 check
2. Using new testcase DBOptionsTest.SetBackgroundFlushThreads
Pull Request resolved: https://github.com/facebook/rocksdb/pull/6701
Reviewed By: ajkr
Differential Revision: D21028010
Pulled By: akankshamahajan15
fbshipit-source-id: 5f949e4a8fd3c32537b637947b7ee09a69cfc7c1
=> Set max_background_flushes dynamically (#6701)

utilities/rate_limiters/write_amp_based_rate_limiter.cc, utilities/rate_limiters/write_amp_based_rate_limiter.h
Old implementation of auto-tuned rate limiter effectively ignore the `SetBytesPerSecond` call from user because of its adaptive nature. Change this semantics in new WriteAmpBasedRateLimiter by setting `max-bytes-per-sec` in auto-tuned mode.
=> Make auto-tuned rate limiter upper bound settable

util/channel.h
Summary:
This change fixes a source issue that caused compile time error which breaks build for many fbcode services in that setup. The size() member function of channel is a const member, so member variables accessed within it are implicitly const as well. This caused error when clang fails to resolve to a constructor that takes std::mutex because the suitable constructor got rejected due to loss of constness for its argument. The fix is to add mutable modifier to the lock_ member of channel.
Pull Request resolved: https://github.com/facebook/rocksdb/pull/6161
Differential Revision: D18967685
Pulled By: maysamyabandeh
fbshipit-source-id: 698b6a5153c3c92eeacb842c467aa28cc350d432
=> Fix build breakage from lock_guard error (#6161)

HISTORY.md, db/db_impl/db_impl.cc, db/db_impl/db_impl_compaction_flush.cc, db/db_options_test.cc, options/db_options.cc, options/db_options.h, options/options_helper.cc
Summary:
1. Add changes so that max_background_flushes can be set dynamically.
2. Add a testcase DBOptionsTest.SetBackgroundFlushThreads which set the
max_background_flushes dynamically using SetDBOptions.
TestPlan:  1. make -j64 check
2. Using new testcase DBOptionsTest.SetBackgroundFlushThreads
Pull Request resolved: https://github.com/facebook/rocksdb/pull/6701
Reviewed By: ajkr
Differential Revision: D21028010
Pulled By: akankshamahajan15
fbshipit-source-id: 5f949e4a8fd3c32537b637947b7ee09a69cfc7c1
Co-authored-by: Akanksha Mahajan <akankshamahajan@fb.com>
=> Set max_background_flushes dynamically (facebook#6701) (#201)

db/compact_files_test.cc, db/compaction/compaction.cc, db/compaction/compaction.h, db/compaction/compaction_job.cc, include/rocksdb/compaction_filter.h
Signed-off-by: qupeng <qupeng@pingcap.com>
This PR adds some information into `CompactionFilter::Context`:
* start_key, end_key, is_end_key_inclusive: indicates the range of the compaction
* file_numbers: file numbers of all involved SST files
* table_properties: table properties of all involved SST files
These fields can be used in `CompactionFilterFactory::create_compaction_filter`.
=> add range for compaction filter context

db/table_cache.cc, db/table_cache.h, env/env_encryption.cc, env/env_test.cc, env/io_posix.cc, env/io_posix.h, include/rocksdb/env.h, port/win/io_win.cc, port/win/io_win.h, util/file_reader_writer.cc, utilities/env_mirror.cc
This change updates the cache key prefix for SST files from relying
on the inode generation number to using a passed-in unique ID. This
ID is composed of a table-cache-specific random ID, as well as the
number of the SST. This should resolve issues around cache collisions
between two different SS tables that happened to have the same
generation number.
Cherry-pick of https://github.com/cockroachdb/rocksdb/pull/61
=> table_cache: Generate unique ID based on db instance, file number

db/table_cache.cc, db/table_cache.h, env/env_encryption.cc, env/env_test.cc, env/io_posix.cc, env/io_posix.h, include/rocksdb/env.h, port/win/io_win.cc, port/win/io_win.h, util/file_reader_writer.cc, utilities/env_mirror.cc
* table_cache: Generate unique ID based on db instance, file number
This change updates the cache key prefix for SST files from relying
on the inode generation number to using a passed-in unique ID. This
ID is composed of a table-cache-specific random ID, as well as the
number of the SST. This should resolve issues around cache collisions
between two different SS tables that happened to have the same
generation number.
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
Co-authored-by: Bilal Akhtar <bilal@cockroachlabs.com>
=> table_cache: Generate unique ID based on db instance, file number (#205)

db/compaction/compaction.cc, db/version_set.cc, db/version_set.h
Signed-off-by: qupeng <qupeng@pingcap.com>
=> allow no_io for VersionSet::GetTableProperties

db/column_family.cc, db/column_family.h, include/rocksdb/rate_limiter.h, utilities/rate_limiters/write_amp_based_rate_limiter.cc, utilities/rate_limiters/write_amp_based_rate_limiter.h
Proactively pace up auto-tuned rate limiter when LSM shape (L0-count/pending-bytes) is close to trigger write stall.
Mitigate tikv/tikv#8962
run wide_table sysbench with 512 threads 100 columns
Before:
After the patch:
=> Pace up limiter before triggering write stall

db/compact_files_test.cc, db/compaction/compaction_iterator.cc, db/db_iter.cc, db/db_iter.h, include/rocksdb/compaction_filter.h, include/rocksdb/iterator.h, utilities/blob_db/blob_db_iterator.h, utilities/ttl/db_ttl_impl.h
This PR supports to access `seqno` for every key/value pairs in compaction filter or iterator.
It's helpful to enhance GC in compaction filter in TiKV.
=> expose seqno from compaction filter and iterator

include/rocksdb/rate_limiter.h, utilities/rate_limiters/write_amp_based_rate_limiter.cc, utilities/rate_limiters/write_amp_based_rate_limiter.h
Add new setter API to `RateLimiter`, only implement it for `WriteAmpBasedRateLimiter`.
=> dynamically set auto_tuned mode of WriteAmpBasedRateLimiter

env/env_test.cc, test_util/testutil.h
> Summary:
> The DecreaseNumBgThreads test keeps failing on Windows in AppVeyor.
> It fails because it depends on a timed wait for the tasks to be dequeued from the threadpool's internal queue, but within the specified time, the task might have not been scheduled onto the newly created threads.
> #6232 tries to fix this by waiting for longer time to let the threads scheduled.
> This PR tries to fix this by replacing the timed wait with a synchronization on the task's internal conditional variable.
> When the number of threads increases, instead of guessing the time needed for the task to be scheduled, it directly blocks on the conditional variable until the task starts running.
> But when thread number is reduced, it still does a timed wait, but this does not lead to the flakiness now, …
=> Fix flaky test DecreaseNumBgThreads (facebook#6393)

db/db_test_util.h, encryption/encryption.cc, encryption/in_memory_key_manager.h, include/rocksdb/encryption.h
fix bug: https://github.com/tikv/tikv/issues/9115
Summary: we need to update encryption metadata via `encryption::DataKeyManager`, which cannot combine with the actual file operation into one atomic operation. In `RenameFile`, when the src_file has been removed, power is off, then we may lost the file info of src_file next restart.
Signed-off-by: Xintao <hunterlxt@live.com>
=> Atomize RenameFile in KeyManagedEncryptedEnv

db/compaction/compaction_job.cc, db/listener_test.cc, include/rocksdb/listener.h
Add listener for subcompaction, only called when there are actually multiple subcompactions executed in parallel.
Pass in `SubcompactionJobInfo` containing:
```
// the id of the column family where the compaction happened.
uint32_t cf_id;
// the name of the column family where the compaction happened.
std::string cf_name;
// the status indicating whether the compaction was successful or not.
Status status;
// the id of the thread that completed this compaction job.
uint64_t thread_id;
// the smallest input level of the compaction.
int base_input_level;
// the output level of the compaction.
int output_level;
```
=> add subcompaction listener

db/db_test_util.cc, db/db_test_util.h, encryption/encryption.cc, env/env_basic_test.cc, file/filename.cc, file/filename.h, test_util/testutil.cc, test_util/testutil.h
https://github.com/tikv/rocksdb/pull/222 used `LinkFile` instead of `RenameFile` api of key manager. But `LinkFile` needs check the dst file information, in `RenameFile` logic, we don't care about that. So just skip encryption for current file.
Signed-off-by: Xintao <hunterlxt@live.com>
=> Atomize Rename operation when encryption is enabled

db/db_test_util.cc, db/db_test_util.h, encryption/encryption.cc, env/env_basic_test.cc, file/filename.cc, file/filename.h, test_util/testutil.cc, test_util/testutil.h
Cherry-picking #224.
https://github.com/tikv/rocksdb/pull/222 used `LinkFile` instead of `RenameFile` api of key manager. But `LinkFile` needs check the dst file information, in `RenameFile` logic, we don't care about that. So just skip encryption for current file.
Signed-off-by: Xintao <hunterlxt@live.com>
=> Atomize Rename operation when encryption is enabled (#224)

encryption/encryption.cc, env/env_basic_test.cc, file/filename.cc, file/filename.h, test_util/testutil.h
Signed-off-by: Xintao <hunterlxt@live.com>
=> Fix the bug that the key manager is not updated during the Rename

db/compact_files_test.cc, db/version_set.cc
cherry-pick of https://github.com/facebook/rocksdb/pull/8024
**Summary:**
When doing CompactFiles on the files of multiple levels(num_level > 2) with L0 is included, the compaction would fail like this.
image
The reason is that in VerifyCompactionFileConsistency it checks the levels between the L0 and base level should be empty, but it regards the compaction triggered by CompactFiles as an L0 -> base level compaction wrongly.
The condition is committed several years ago, considering num_input_levels == output_level - start_level + 1 at that time, whereas it not correct anymore.
if (vstorage->compaction_style_ == kCompactionStyleLevel &&
c->start_level() == 0 && c->num_input_levels() > 2U)
So this PR just deletes the incorrect check.
**Test Plan:**
make check
=> fix compaction error for compact files

util/crc32c_arm64.cc, util/crc32c_arm64.h
Cherry-picking the following ARM crc32 improvements from upstream:
```
a378a4c2a 2019-09-12 54057110+houbingji.. arm64 crc prefetch optimise (#5773)
26293c89a 2019-08-23 53242408+zhiwei-da.. crc32c_arm64 performance optimization (#5675)
```
=> Cherry-picking ARM crc32 improvement

port/jemalloc_helper.h
Now it does not compile at my place with clang 11 and 12 if jemalloc is enabled.
```
> CC=clang CXX=clang++ cargo build --features "jemalloc,static_libcpp"
...
In file included from /home/yilin/Code/rust-rocksdb/librocksdb_sys/rocksdb/db/malloc_stats.cc:16:
/home/yilin/Code/rust-rocksdb/librocksdb_sys/rocksdb/port/jemalloc_helper.h:43:18: error: 'mallocx' is missing exception specification '__attribute__((nothrow))' [-Werror,-Wmissing-exception-spec]
extern "C" void* mallocx(size_t, int) __attribute__((__weak__));
^
__attribute__((nothrow))
/home/yilin/Code/rust-rocksdb/target/debug/build/tikv-jemalloc-sys-bafc6265fb6ded08/out/include/jemalloc/jemalloc.h:385:19: note: expanded from macro 'mallocx'
^
/home/yilin/Code/rust-rocksdb/target/debug/build/tikv-jemalloc-sys-bafc6265fb6ded08/out/inc …
```
=> Fix compilation when jemalloc is enabled on clang 

tools/sst_dump_tool.cc
=> Fix sst_dump not able to open ingested file (#6673)

db/compaction/compaction_picker_test.cc, db/version_builder.cc, db/version_builder_test.cc, db/version_set.cc, db/version_set.h, db/version_set_test.cc
Cherry-pick the following commits:
```
* 75e7cb923 Make it possible to look up files by number in VersionStorageInfo (facebook/rocksdb#6862)
* 7861b5a3d Improve consistency checks in VersionBuilder (facebook/rocksdb#6901)
* 37c7c7175 Revisit the handling of the case when a file is re-added to the same level (facebook/rocksdb#6939)
```
=> Cherry-pick version builder related changes
